baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-theme"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "blog"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  # Enable to show table of contents for posts
  Toc = true
  # Contact form action
  contactFormAction = ""
  # Uses Netlify to handle contact form?
  contactFormNetlify = true

[languages]
  [languages.en]
    title = "Stephen Baker"
    subtitle = "A Networking blog"
    keywords = "ccie"
    copyright = "© 2022 | stphnbkr.com "
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "stphnbkr.com"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/archive"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Search"
        url = "/tags"


[outputFormats]
  [outputFormats.searchIndex]
    baseName = "search"
    mediaType = "application/json"

[outputs]
  home = [ "HTML", "RSS", "SearchIndex" ]
